"""
这是树莓派rp2040 pico w 的micropython的machine库的一些接口提示
"""

class Pin:
    
    OUT = 1
    
    def __init__(self, pin_number, mode=OUT): ...
    
    def toggle(self): ...

    def value(self,number): ...


class I2C:
    
    def __init__(self,i2z_id:int,scl:Pin,sda:Pin,freq=400000): ...
    
    def writeto_mem(self,address:int,PWR_MGMT_1:int,data:bytes): ...
    
    def scan(self) -> list: ...
    
    def readfrom_mem(self,addr:int,reg_addr,int) -> bytes: ...
    
class UART:
    def __init__(self,id:int,波特率:int): ...
    
    def write(self,data): ...
    
    def read(self,) -> bytes: ...
    
    def any(self) -> bool: ...
